export enum Patterns {
  CREATE_USER = 'USER_CREATE_USER',
  GET_WITH_EMAIL = 'USER_GET_WITH_EMAIL',
  GET_WITH_ID = 'USER_GET_WITH_ID',
  GET_WITH_RPT = 'USER_GET_WITH_RPT',
  UPDATE_PROFILE_ID = 'USER_UPDATE_PROFILE_ID',
  UPDATE_RPT = 'USER_UPDATE_RPT',
  UPDATE_PASSWORD = 'USER_UPDATE_PASSWORD',
  SSO_LOGIN = 'USER_SSO_LOGIN',
  GOOGLE_LOGIN = 'USER_GOOGLE_LOGIN',
  PROFILE_CREATE = 'PROFILE_CREATE',
  PROFILE_GET_WITH_ID = 'PROFILE_GET_ID',
}
