export enum Patterns {
  CREATE_USER = 'USER_CREATE_USER',
  GET_WITH_EMAIL = 'USER_GET_WITH_EMAIL',
  GET_WITH_ID = 'USER_GET_WITH_ID',
  GET_WITH_RPT = 'USER_GET_WITH_RPT',
  UPDATE_PROFILE_ID = 'USER_UPDATE_PROFILE_ID',
  UPDATE_RPT = 'USER_UPDATE_RPT',
  UPDATE_PASSWORD = 'USER_UPDATE_PASSWORD',
  COMPARE_PASSWORD = 'USER_COMPARE_PASSWORD',
}
